[WIP] First Draft of OPEA Triage Tool
opea-project/GenAIExamples pull request #1185
Opened 2024-11-23 00:35 UTC by louie-tsai

## Description

To help customers debug OPEA issues, we create a Triage Tool to test and gather needed information for debugging.

For the first draft, it is for ChatQnA.

**The Triage Tools will run some simple tests including:**
1. health_check
2. micorservice testings
3. statistics 

**Below information will be gather after above testings** 
1. system info
2. env variable info
3. all docker logs for microservices
4. (optional) profiling results like vllm pytorch profiling

**Report:**
plan to have a HTML report.
Right now we have
1. simple console output
2. simple html report

console output
Below is the screenshot for console output.
![image](https://github.com/user-attachments/assets/93948b75-7bec-484b-ba0f-5d50c576be93)

html report
![image](https://github.com/user-attachments/assets/0310c9ff-3ca9-4ef7-86c5-ff5def8e0f9a)

## Issues

`n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

NA

## Tests

Manual Testing

2024-11-25 06:48 UTC, louie-tsai commented
a sample report zip file
[ChatQnA_Xeon.json_11-25_06-34.zip](https://github.com/user-attachments/files/17898512/ChatQnA_Xeon.json_11-25_06-34.zip)

2024-11-27 19:43 UTC, louie-tsai commented
[ToDo] : understand whether we need debug RESTful API request here or using Telemetery

2024-11-27 23:00 UTC, alexsin368 commented on ChatQnA/tests/ChatQnA_Xeon.json
> +      "service": "retrival",
typo: retrieval

2024-11-27 23:01 UTC, alexsin368 commented on ChatQnA/tests/ChatQnA_Xeon.json
> +      "service": "retrival",
```suggestion
      "service": "retrieval",
```

2024-11-27 23:01 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +#unittest.TestLoader.sortTestMethodsUsing = lambda self, a, b: (a < b) - (a > b)
remove commented out code

2024-11-27 23:02 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #print("Command exit status/return code : ", p_status)
remove commented out code

2024-11-27 23:02 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #print(i["service"])
remove commented out code

2024-11-27 23:02 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +            #print(row)
remove commented out code

2024-11-27 23:02 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +    #print(df)
remove commented out code

2024-11-27 23:03 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +    #docker_index = df.loc[df['PORTS'] == port]
remove commented out code

2024-11-27 23:03 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #print(command_line_param)
remove commented out code

2024-11-27 23:03 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #print(df)
remove commented out code

2024-11-27 23:03 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #print(df)
remove commented out code

2024-11-27 23:03 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #status, output = RunCmd().run("docker ps")
remove commented out code

2024-11-27 23:04 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #self.assertEqual(response_status_code, 200)
remove commented out code

2024-11-27 23:04 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #response_status_code  = utils.service_test(self.ip, port, endpoint_name, data, self.triage_report, self.triage_level)
remove commented out code

2024-11-27 23:04 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #self.assertEqual(response_status_code, 200)
remove commented out code

2024-11-27 23:04 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #self.assertEqual(response_status_code, 200)
remove commented out code

2024-11-27 23:04 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #self.assertEqual(response_status_code, 200)
remove commented out code

2024-11-27 23:04 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #self.assertEqual(response_status_code, 200)
remove commented out code

2024-11-27 23:04 UTC, alexsin368 commented on ChatQnA/tests/Triage.py
> +        #self.assertEqual(response_status_code, 200)
remove commented out code

2024-11-27 23:05 UTC, alexsin368 requested changes
Remove any commented out code

2024-12-23 04:01 UTC, xiguiw commented
@louie-tsai 
This feature is useful!
Will you check the CI failure? 
I will push development team to review it.

2025-02-25 14:00 UTC, xiguiw commented
@louie-tsai 
Are you still working on this?

2025-04-01 08:08 UTC, xiguiw commented
@louie-tsai 

Are you still working on this?
Would you keep this PR on, or just close it?

2025-04-17 02:50 UTC, xiguiw commented
@louie-tsai 

Please submit new PR for this if needed.
Close this one as it is inactive more than weeks.

2025-04-17 02:50 UTC, closed without merging