Add microservice resources to no_proxy in the main ChatQnA README
opea-project/GenAIExamples pull request #1269
Opened 2024-12-19 01:05 UTC by daniel-de-leon-user293

## Description

This PR only adds direction in the main ChatQnA README to append the microservice resources needed for proxy'd environments in the `no_proxy` env variable. These commands can be found in the individual hardware README's but just adding to the main README for more visibility.

## Issues

https://github.com/opea-project/GenAIExamples/issues/1247

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [x] Others (enhancement, documentation, validation, etc.)

## Dependencies

N/A

## Tests

N/A

2024-12-19 01:12 UTC, ashahba requested changes

2024-12-19 01:12 UTC, ashahba commented on ChatQnA/README.md
> +   > Notice that you can only choose **one** hardware option below to set up envs according to your hardware. Other that the port numbers may be set incorrectly.
Do you mean:
`Other than` or `Other than that`?

2024-12-19 01:19 UTC, ashahba commented on ChatQnA/README.md
> +   > Notice that you can only choose **one** hardware option below to set up envs according to your hardware. Other that the port numbers may be set incorrectly.
I think the correct sentence should be:
`Also make sure port numbers are set correctly too.`

2024-12-19 01:27 UTC, ashahba approved these changes
LGTM!

2024-12-27 08:11 UTC, yinghu5 approved these changes
LGTM

2024-12-27 08:14 UTC, merged