Updated READMEs for kubernetes example pipelines
opea-project/GenAIExamples pull request #353
Opened 2024-06-28 21:17 UTC by mkbhanda

Signed-off-by: mkbhanda <malini.bhandaru@intel.com>

## Description

Updated common READMEs and example specific READMEs for the 4 example pipelines for Kubernetes

## Issues

List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

2024-06-28 23:41 UTC, ashahba requested changes
Thanks @mkbhanda for this PR.
Most comments are minor.

2024-06-28 23:41 UTC, ashahba commented on DocSum/kubernetes/README.md
> +
I'd add a line here and warn users that:
- **Note:** The following environment variables are specific to user's environment setup and need to be obtained by them prior to export.

2024-06-28 23:41 UTC, ashahba commented on DocSum/kubernetes/README.md
> +kubectl create ns $(ns)
This has to be:
```
kubectl create ns ${ns}
```

2024-06-28 23:41 UTC, ashahba commented on DocSum/kubernetes/README.md
> +kubectl get service -n $(ns)
This one too:
```
kubectl get service -n ${ns}
```

2024-06-28 23:41 UTC, ashahba commented on DocSum/kubernetes/README.md
> +kubectl get gmconnectors.gmc.opea.io -n $(ns)
`$(ns)` -> `${ns}`

2024-06-28 23:41 UTC, ashahba commented on DocSum/kubernetes/README.md
> +kubectl exec "$CLIENT_POD" -n $ns -- curl $accessUrl  -X POST  -d '{"query":"Text Embeddings Inference (TEI) is a toolkit for deploying and serving open source text embeddings and sequence classifica
We only need one space before `-X`, `-d` and `-H`

2024-07-01 22:25 UTC, ashahba approved these changes
LGTM!

2024-07-09 01:23 UTC, kevinintel approved these changes

2024-07-10 01:03 UTC, merged