[Doc] Update ChatQnA flow chart
opea-project/GenAIExamples pull request #542
Opened 2024-08-07 07:46 UTC by xiguiw

Draw flow-chat with mermaid script. 
make it easy to be maintained.

2024-08-07 07:51 UTC, xiguiw commented
The output flow-chart is:
![image](https://github.com/user-attachments/assets/0e927cdb-a1a1-4f06-8d87-209dc8ac0715)

2024-08-07 15:12 UTC, louie-tsai reviewed
some minor changes.
Might have more feedbacks but we might need to bring up the different solution (langchain, llama-index, and etc) used in microservice.

2024-08-08 02:09 UTC, hshen14 approved these changes

2024-08-08 03:31 UTC, louie-tsai reviewed
Suggest to change the flowchart as below diagram.
please help to review it.

```mermaid
graph LR
    subgraph ChatQnA-MegaService["ChatQnA-MegaService"]
        direction LR
        EM([Embedding 'LangChain TEI' <br>6000])
        RET([Retrieval 'LangChain Redis'<br>7000])
        RER([Rerank 'TEI'<br>8000])
        LLM([LLM 'text-generation TGI'<br>8008])
    end

    direction TB
    TEI_EM{{TEI embedding service<br>8090}}
    VDB{{Vector DB<br>8001}}
    %% Vector DB interaction
    TEI_EM -.->|d|VDB

    DP([OPEA Data Preparation<br>6007])
    LLM_gen{{TGI/vLLM/ollama Service}}

    direction TB
    RER([Rerank 'TEI'<br>8000])
    TEI_RER{{TEI Reranking service<br>8808}}

    subgraph User Interface
        direction TB
        a[User Input Query]
        Ingest[Ingest data]
        UI[UI server<br>Port: 5173]
    end

    subgraph ChatQnA GateWay
        direction LR
        GW[ChatQnA GateWay<br>Port: 8888]
    end

    %% Data Preparation flow
    %% Ingest data flow
    direction LR
    Ingest[Ingest data] -->|a| UI
    UI -->|b| DP
    DP -.->|c| TEI_EM

    %% Questions interaction
    direction LR
    a[User Input Query] -->|1| UI
    UI -->|2| GW
    GW <==>|3| ChatQnA-MegaService
    EM ==>|4| RET
    RET ==>|5| RER
    RER ==>|6| LLM


    %% Embedding service flow
    direction TB
    EM -.->|3'| TEI_EM
    RET -.->|4'| TEI_EM
    RER -.->|5'| TEI_RER
    LLM -.->|6'| LLM_gen

    subgraph Legend
        X([Micsrservice])
        Y{{Server API}}
    end
```

2024-08-08 03:31 UTC, louie-tsai commented on ChatQnA/README.md
> +    subgraph ChatQnA Mega Service
```suggestion
    subgraph ChatQnA-MegaService["ChatQnA-MegaService"]
```

2024-08-08 03:31 UTC, louie-tsai commented on ChatQnA/README.md
> +        EM([OPEA Embedding<br>6000])
```suggestion
        EM([Embedding 'LangChain TEI' <br>6000])
```

2024-08-08 03:31 UTC, louie-tsai commented on ChatQnA/README.md
> +        RET([OPEA Retrieval<br>7000])
```suggestion
        RET([Retrieval 'LangChain Redis'<br>7000])
```

2024-08-08 03:31 UTC, louie-tsai commented on ChatQnA/README.md
> +        RER([OPEA Reranking<br>8000])
```suggestion
        RER([Rerank 'TEI'<br>8000])
```

2024-08-08 03:31 UTC, louie-tsai commented on ChatQnA/README.md
> +        LLM([OPEA LLM 'text generate'<br>8008])
```suggestion
       LLM([LLM 'text-generation TGI'<br>8008])
```

2024-08-08 03:31 UTC, louie-tsai commented on ChatQnA/README.md
> +    GW ==>|3| EM
```suggestion
    GW ==>|3|  ChatQnA-MegaService
```

2024-08-08 03:31 UTC, louie-tsai commented on ChatQnA/README.md
> +    LLM ==>|7| GW
```suggestion
    
```

2024-08-08 03:31 UTC, louie-tsai commented on ChatQnA/README.md
> +    EM -.->|3'| TEI_EM
```suggestion
    EM -.->|3'| TEI_EM
    RET -.->|4'| TEI_EM
```

2024-08-08 03:31 UTC, louie-tsai commented on ChatQnA/README.md
> +        Y{{Server API}}
```suggestion
        Y{{Service from industry peers}}
        Z[Gateway]
```

2024-08-08 18:58 UTC, louie-tsai commented on ChatQnA/README.md
> +       LLM([LLM 'text-generation TGI'<br>8008])
```suggestion
       LLM([LLM 'text-generation TGI'<br>9000])
```

2024-08-08 20:00 UTC, ctao456 commented
Comment to review

2024-08-08 21:33 UTC, alexsin368 commented on ChatQnA/README.md
> +    GW ==>|3|  ChatQnA-MegaService
Remove extra space before "ChatQnA-MegaService". This is causing the chart to not show up on the README.

2024-08-08 21:34 UTC, alexsin368 requested changes
Fix error so that chart will display

2024-08-08 21:46 UTC, ctao456 requested changes

2024-08-08 21:46 UTC, ctao456 commented on ChatQnA/README.md
> +    LLM_gen{{TGI/vLLM/ollama Service}}
`    LLM_gen{{TGI/vLLM/ollama Service<br>9009}}
`

2024-08-08 21:46 UTC, ctao456 commented on ChatQnA/README.md
> +    TEI_EM{{TEI embedding service<br>8090}}
`    TEI_EM{{TEI embedding service<br>6006}}
`

2024-08-16 06:43 UTC, letonghan reviewed
Hi @xiguiw , the `Retrieval` microservice also need to access the `Vector DB` service. I think another arrow is needed.

2024-08-21 23:55 UTC, louie-tsai commented
> Hi @xiguiw , the `Retrieval` microservice also need to access the `Vector DB` service. I think another arrow is needed.

Does Retrieval access VectorDB directly or access VectorDB via TEI Embedding service?

2024-08-23 01:04 UTC, louie-tsai commented
updated flowchart according to wiki
```mermaid
---
config:
  flowchart:
    nodeSpacing: 100
    rankSpacing: 100
    curve: linear
  theme: base
  themeVariables:
    fontSize: 42px
---
flowchart LR
    %% Colors %%
    classDef blue fill:#ADD8E6,stroke:#ADD8E6,stroke-width:2px,fill-opacity:0.5
    classDef orange fill:#FBAA60,stroke:#ADD8E6,stroke-width:2px,fill-opacity:0.5
    classDef orchid fill:#C26DBC,stroke:#ADD8E6,stroke-width:2px,fill-opacity:0.5
    classDef invisible fill:transparent,stroke:transparent;
    style ChatQnA-MegaService stroke:#000000
    %% Subgraphs %%
    subgraph ChatQnA-MegaService["ChatQnA-MegaService"]
        direction LR
        EM([Embedding <br>6000]):::blue
        RET([Retrieval <br>7000]):::blue
        RER([Rerank <br>8000]):::blue
        LLM([LLM <br>9000]):::blue
    end
    subgraph User Interface
        direction TB
        a([User Input Query]):::orchid
        Ingest([Ingest data]):::orchid
        UI([UI server<br>Port: 5173]):::orchid
    end
    subgraph ChatQnA GateWay
        direction LR
        invisible1[ ]:::invisible
        GW([ChatQnA GateWay<br>Port: 8888]):::orange
    end
    subgraph .
        X([Micsrservice]):::blue
        Y{{Service from industry peers}}
        Z([Gateway]):::orange
        Z1([UI]):::orchid
    end



    %% Data Preparation flow
    %% Ingest data flow
    direction LR
    Ingest[Ingest data] -->|a| UI
    UI -->|b| DP
    DP -.->|c| TEI_EM

    %% Questions interaction
    direction LR
    a[User Input Query] -->|1| UI
    UI -->|2| GW
    GW <==>|3| ChatQnA-MegaService
    EM ==>|4| RET
    RET ==>|5| RER
    RER ==>|6| LLM


    %% Embedding service flow
    direction TB
    EM -.->|3'| TEI_EM
    RET -.->|4'| R_RET
    RER -.->|5'| TEI_RER
    LLM -.->|6'| LLM_gen

    direction TB
    TEI_RER{{Reranking service<br>'TEI'<br>8808}}
    TEI_EM{{Embedding service <br>'TEI LangChain'<br>6006}}
    R_RET{{Retriever service <br>'LangChain Redis'<br>7000}}
    VDB{{Vector DB<br>'Redis'<br>8001}}
    %% Vector DB interaction
    TEI_EM <-.->|d|VDB
    R_RET <-.->|d|VDB

    DP([Data Preparation<br>'LangChain Redis'<br>6007])
    LLM_gen{{LLM Service <br>'TGI'<br>9009}}


```

2024-08-26 19:20 UTC, louie-tsai approved these changes

2024-08-26 19:20 UTC, merged