Make all xeon tgi image version consistent
opea-project/GenAIExamples pull request #851
Opened 2024-09-19 09:51 UTC by zhlsunshine

## Description

Make all xeon tgi image version consistent

## Issues

`n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

`n/a`.

## Tests

`n/a`.

2024-09-19 10:00 UTC, lvliang-intel commented on ChatQnA/kubernetes/intel/cpu/xeon/manifest/chatqna.yaml
The docker image 'ghcr.io/huggingface/text-generation-inference:sha-e4201f4-intel-cpu' is intel cpu optimized tgi image. We should not use "ghcr.io/huggingface/text-generation-inference:2.2.0" for Intel CPU.

2024-09-19 10:06 UTC, zhlsunshine commented on ChatQnA/kubernetes/intel/cpu/xeon/manifest/chatqna.yaml
Hi @lvliang-intel, if so, should I set all the xeon tgi images to `ghcr.io/huggingface/text-generation-inference:sha-e4201f4-intel-cpu`?

2024-09-19 10:11 UTC, zhlsunshine commented on ChatQnA/kubernetes/intel/cpu/xeon/manifest/chatqna.yaml
I notice that there are at least 3 version images are using on xeon for the examples, `ghcr.io/huggingface/text-generation-inference:sha-e4201f4-intel-cpu`, `ghcr.io/huggingface/text-generation-inference:2.1.0` and `ghcr.io/huggingface/text-generation-inference:sha-e4201f4-intel-cpu`, should I consistent them as one?

2024-09-19 11:16 UTC, zhlsunshine commented
Hi @lvliang-intel, as we discussed, let's use `ghcr.io/huggingface/text-generation-inference:sha-e4201f4-intel-cpu` as the tgi image on xeon for all examples.

2024-09-20 07:39 UTC, zhlsunshine commented
Hi @lvliang-intel, I replace the `ghcr.io/huggingface/text-generation-inference:sha-e4201f4-intel-cpu` with `ghcr.io/huggingface/text-generation-inference:latest-intel-cpu`

2024-09-20 07:55 UTC, lvliang-intel approved these changes

2024-09-22 14:37 UTC, lvliang-intel commented on ChatQnA/kubernetes/intel/cpu/xeon/manifest/chatqna.yaml
yes, please use 'ghcr.io/huggingface/text-generation-inference:sha-e4201f4-intel-cpu'. We will update it in case there is an official TGI intel cpu optimized version.

2024-09-23 04:46 UTC, lianhao requested changes
why the CI manifest test is missing? We need them to make sure it's working

2024-09-23 09:25 UTC, zhlsunshine commented
Hi @lvliang-intel @lianhao @chensuyue, after discussed with Intel Xeon TGI image support engineer, we'd better to use the specified version of TGI image, such as `ghcr.io/huggingface/text-generation-inference:sha-e4201f4-intel-cpu`, instead  `ghcr.io/huggingface/text-generation-inference:latest-intel-cpu` which would update every day.

2024-09-23 09:59 UTC, chensuyue commented
Please resolve the conflicts.

2024-09-23 10:10 UTC, zhlsunshine commented
> Please resolve the conflicts.

Hi @chensuyue sure, done!

2024-09-24 03:19 UTC, merged